# fly.toml app configuration file generated for spectacled-proxy on 2026-08-21T08:56:57Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'spectacled-proxy'
primary_region = 'fra'

[build]
  dockerfile = 'server/Dockerfile'

[env]
  PORT = '8080'
  PROXY_ALLOWED_ORIGINS = 'https://spectacled.techbee.at'
  PROXY_REQUIRE_HTTPS_TARGET = 'true'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
