package at.techbee.spectacled.theme.tasks

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme

val lightTasksScheme = lightColorScheme(
    primary = TasksColors.primaryLight,
    onPrimary = TasksColors.onPrimaryLight,
    primaryContainer = TasksColors.primaryContainerLight,
    onPrimaryContainer = TasksColors.onPrimaryContainerLight,
    secondary = TasksColors.secondaryLight,
    onSecondary = TasksColors.onSecondaryLight,
    secondaryContainer = TasksColors.secondaryContainerLight,
    onSecondaryContainer = TasksColors.onSecondaryContainerLight,
    tertiary = TasksColors.tertiaryLight,
    onTertiary = TasksColors.onTertiaryLight,
    tertiaryContainer = TasksColors.tertiaryContainerLight,
    onTertiaryContainer = TasksColors.onTertiaryContainerLight,
    error = TasksColors.errorLight,
    onError = TasksColors.onErrorLight,
    errorContainer = TasksColors.errorContainerLight,
    onErrorContainer = TasksColors.onErrorContainerLight,
    background = TasksColors.backgroundLight,
    onBackground = TasksColors.onBackgroundLight,
    surface = TasksColors.surfaceLight,
    onSurface = TasksColors.onSurfaceLight,
    surfaceVariant = TasksColors.surfaceVariantLight,
    onSurfaceVariant = TasksColors.onSurfaceVariantLight,
    outline = TasksColors.outlineLight,
    outlineVariant = TasksColors.outlineVariantLight,
    scrim = TasksColors.scrimLight,
    inverseSurface = TasksColors.inverseSurfaceLight,
    inverseOnSurface = TasksColors.inverseOnSurfaceLight,
    inversePrimary = TasksColors.inversePrimaryLight,
    surfaceDim = TasksColors.surfaceDimLight,
    surfaceBright = TasksColors.surfaceBrightLight,
    surfaceContainerLowest = TasksColors.surfaceContainerLowestLight,
    surfaceContainerLow = TasksColors.surfaceContainerLowLight,
    surfaceContainer = TasksColors.surfaceContainerLight,
    surfaceContainerHigh = TasksColors.surfaceContainerHighLight,
    surfaceContainerHighest = TasksColors.surfaceContainerHighestLight,
)

val darkTasksScheme = darkColorScheme(
    primary = TasksColors.primaryDark,
    onPrimary = TasksColors.onPrimaryDark,
    primaryContainer = TasksColors.primaryContainerDark,
    onPrimaryContainer = TasksColors.onPrimaryContainerDark,
    secondary = TasksColors.secondaryDark,
    onSecondary = TasksColors.onSecondaryDark,
    secondaryContainer = TasksColors.secondaryContainerDark,
    onSecondaryContainer = TasksColors.onSecondaryContainerDark,
    tertiary = TasksColors.tertiaryDark,
    onTertiary = TasksColors.onTertiaryDark,
    tertiaryContainer = TasksColors.tertiaryContainerDark,
    onTertiaryContainer = TasksColors.onTertiaryContainerDark,
    error = TasksColors.errorDark,
    onError = TasksColors.onErrorDark,
    errorContainer = TasksColors.errorContainerDark,
    onErrorContainer = TasksColors.onErrorContainerDark,
    background = TasksColors.backgroundDark,
    onBackground = TasksColors.onBackgroundDark,
    surface = TasksColors.surfaceDark,
    onSurface = TasksColors.onSurfaceDark,
    surfaceVariant = TasksColors.surfaceVariantDark,
    onSurfaceVariant = TasksColors.onSurfaceVariantDark,
    outline = TasksColors.outlineDark,
    outlineVariant = TasksColors.outlineVariantDark,
    scrim = TasksColors.scrimDark,
    inverseSurface = TasksColors.inverseSurfaceDark,
    inverseOnSurface = TasksColors.inverseOnSurfaceDark,
    inversePrimary = TasksColors.inversePrimaryDark,
    surfaceDim = TasksColors.surfaceDimDark,
    surfaceBright = TasksColors.surfaceBrightDark,
    surfaceContainerLowest = TasksColors.surfaceContainerLowestDark,
    surfaceContainerLow = TasksColors.surfaceContainerLowDark,
    surfaceContainer = TasksColors.surfaceContainerDark,
    surfaceContainerHigh = TasksColors.surfaceContainerHighDark,
    surfaceContainerHighest = TasksColors.surfaceContainerHighestDark,
)
