package at.techbee.spectacled.screens.core.presentation.components


import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.toArgb
import at.techbee.spectacled.screens.core.presentation.components.PathDataSvgConverter.encodeMetadata
import at.techbee.spectacled.screens.core.presentation.components.PathDataSvgConverter.fromSvg
import at.techbee.spectacled.screens.core.presentation.components.PathDataSvgConverter.toSvg
import kotlin.math.max
import kotlin.math.round

// ============================================================================
// AI-GENERATED CODE
// Generated by: Claude (Anthropic) — model "Claude Sonnet 5"
// Generated on: 2026-07-02
// ============================================================================

/*
 * Pure Kotlin (uses only Compose Multiplatform's common `ui-graphics`/`ui-geometry`
 * types — Offset, Color, toArgb() — none of which are Android-only). Drop this file
 * into your `commonMain` source set alongside your existing `PathData` model.
 *
 * This is a variant of the earlier DrawingSvgConverter, adapted to operate directly on
 * your own `PathData`/`Offset`/`Color` types instead of a separate internal model, so
 * there's no mapping step between your canvas and the converter.
 *
 * Strategy (unchanged from before):
 *  - The visual geometry is written as standard SVG <path> elements using quadratic
 *    Bézier curves that mirror the smoothing your DrawingCanvas already applies at
 *    render time (midpoint-as-control-point), so the SVG looks like your canvas in any
 *    SVG-capable viewer.
 *  - Full-fidelity data (exact point coordinates, id, color, thickness) is additionally
 *    embedded in a <metadata> CDATA block using a tiny custom text format.
 *  - On import, ONLY that metadata block is trusted as editable stroke data — see
 *    fromSvg() for why the visible <path> geometry is never parsed back.
 */

/**
 * Converts between `List<PathData>` (your canvas's own stroke model) and an SVG string
 * suitable for attaching to a CalDAV note (e.g. as a base64-encoded `ATTACH` property
 * with `FMTTYPE=image/svg+xml`).
 *
 * The exported SVG is dual-purpose:
 *  1. Standard `<path>` elements make the drawing viewable in *any* SVG-capable client.
 *  2. An embedded `<metadata>` block preserves the exact `PathData` list (id, color,
 *     thickness, every point) so this app — and only this app — can losslessly
 *     reconstruct it on import.
 *
 * Importing deliberately trusts only that metadata block, never the visible `<path>`
 * geometry. See [fromSvg].
 */
object PathDataSvgConverter {

    data class DrawingData(
        val paths: List<PathData>,
        val width: Float,
        val height: Float
    )

    /**
     * Serializes a list of [PathData] (one per stroke) to an SVG document string.
     *
     * Each stroke becomes one `<path>` element. The path geometry uses quadratic Bézier
     * segments — control point at the midpoint of each consecutive point pair, endpoint
     * at the next point — mirroring the smoothing `DrawingCanvas.drawPath()` applies at
     * render time, so the exported SVG visually matches what your canvas shows. A
     * trailing `<metadata>` CDATA block encodes the exact `PathData` (id, color,
     * thickness, raw points) for lossless round-tripping via [fromSvg].
     *
     * @param paths The strokes to serialize, in draw order.
     * @param canvasWidth Width of the canvas the strokes were drawn on, used for the
     *   SVG `viewBox`. If `null`, it's derived from the maximum x-coordinate across all
     *   points (assumes the canvas origin is at `(0, 0)`).
     * @param canvasHeight Same as [canvasWidth] but for height / the y-axis.
     * @return A complete, self-contained SVG document as a string (UTF-8 text, not encoded).
     */
    fun toSvg(
        paths: List<PathData>,
        canvasWidth: Float? = null,
        canvasHeight: Float? = null
    ): String {
        val (boundW, boundH) = boundingSize(paths)
        val width = canvasWidth ?: boundW
        val height = canvasHeight ?: boundH

        val sb = StringBuilder()
        sb.append("<svg xmlns=\"http://www.w3.org/2000/svg\" ")
        sb.append("viewBox=\"0 0 ${width.fmt()} ${height.fmt()}\" ")
        sb.append("width=\"${width.fmt()}\" height=\"${height.fmt()}\">\n")

        for (path in paths) {
            if (path.paths.isEmpty()) continue
            val rgb = "#" + (path.color.toArgb() and 0x00FFFFFF).toUInt().toString(16).padStart(6, '0')
            val alpha = path.color.alpha
            sb.append("  <path d=\"${pathData(path.paths)}\" ")
            sb.append("fill=\"none\" stroke=\"$rgb\" ")
            sb.append("stroke-opacity=\"${alpha.fmt()}\" ")
            sb.append("stroke-width=\"${path.thickness.fmt()}\" ")
            sb.append("stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n")
        }

        // Lossless payload — the ONLY thing fromSvg() will trust as editable data.
        sb.append("  <metadata id=\"drawingData\"><![CDATA[\n")
        sb.append(encodeMetadata(width, height, paths))
        sb.append("  ]]></metadata>\n")
        sb.append("</svg>")
        return sb.toString()
    }

    /**
     * Parses an SVG string back into an editable [DrawingData], but ONLY if it
     * contains this class's own embedded `<metadata>` block (see [encodeMetadata] for
     * the format).
     *
     * This intentionally does not attempt to reconstruct strokes from `<path>` geometry.
     * An SVG attachment may have been edited, replaced, or created by a different CalDAV
     * client — its path data could use curves, transforms, groups, multiple subpaths, or
     * anything else valid SVG allows, none of which reliably maps back to `PathData`.
     * Rather than guess and risk silently corrupting or misrepresenting that data, this
     * function refuses to touch it.
     *
     * @param svg The SVG document string to parse.
     * @return The reconstructed, editable [DrawingData] if — and only if — a valid
     *   metadata block produced by [toSvg] is present. Returns `null` for any other SVG
     *   (foreign, hand-edited, corrupted, or missing the block entirely); the caller
     *   should treat a `null` result as "render this attachment as a flat, read-only
     *   image, don't offer stroke-level editing."
     */
    fun fromSvg(svg: String): DrawingData? = parseMetadata(svg)

    // -----------------------------------------------------------------
    // Geometry (write-only) — used to emit <path> elements so any SVG
    // viewer can render the drawing. Never parsed back; see fromSvg().
    // -----------------------------------------------------------------

    /**
     * Builds an SVG path `d` attribute value for one stroke, as a sequence of quadratic
     * Bézier segments: `M x0 y0 Q cx1 cy1 x1 y1 Q cx2 cy2 x2 y2 ...`, where each control
     * point is the midpoint of the two points it connects. This mirrors the smoothing
     * your `DrawingCanvas.drawPath()` composable applies at render time.
     *
     * @param points The stroke's raw points, in order.
     * @return The `d` attribute value (without surrounding quotes), or an empty string
     *   if [points] is empty.
     */
    private fun pathData(points: List<Offset>): String {
        if (points.isEmpty()) return ""
        val sb = StringBuilder("M ${points[0].x.fmt()} ${points[0].y.fmt()} ")
        for (i in 1..points.lastIndex) {
            val from = points[i - 1]
            val to = points[i]
            val cx = (from.x + to.x) / 2
            val cy = (from.y + to.y) / 2
            sb.append("Q ${cx.fmt()} ${cy.fmt()} ${to.x.fmt()} ${to.y.fmt()} ")
        }
        return sb.toString().trim()
    }

    /**
     * Computes a fallback canvas size from the strokes themselves, used by [toSvg] when
     * no explicit `canvasWidth`/`canvasHeight` is supplied.
     *
     * @param paths The strokes to measure.
     * @return The maximum x and y coordinate found across all points (assuming the
     *   canvas origin is `(0, 0)`), or `(0f, 0f)` if [paths] is empty or contains no points.
     */
    private fun boundingSize(paths: List<PathData>): Pair<Float, Float> {
        var maxX = 0f
        var maxY = 0f
        for (path in paths) {
            for (o in path.paths) {
                maxX = max(maxX, o.x)
                maxY = max(maxY, o.y)
            }
        }
        return maxX to maxY
    }

    // -----------------------------------------------------------------
    // Lossless metadata block: simple line-based format, no JSON/XML lib
    // needed. Example:
    //
    //   W:800.0,600.0
    //   S:2026-07-02T10:15:30.123Z|FF000000|5.0
    //   12.0,8.5
    //   14.2,9.1
    //   S:2026-07-02T10:15:31.987Z|FF3366CC|30.0
    //   ...
    //
    // Note: the "S:" header uses '|' as a separator (not ',') so that `id` values
    // (e.g. ISO timestamps) can't collide with the numeric point lines' ',' separator.
    // If your `id` values could ever contain '|' or a newline, swap in a different
    // delimiter or escape it before relying on this format.
    // -----------------------------------------------------------------

    private val CDATA_REGEX = Regex(
        "<metadata[^>]*>\\s*<!\\[CDATA\\[([\\s\\S]*?)]]>\\s*</metadata>"
    )

    /**
     * Encodes canvas size and a list of [PathData] as the plain-text payload embedded
     * inside the SVG's `<metadata>` CDATA block.
     *
     * @param canvasWidth Canvas width to record (see [toSvg]).
     * @param canvasHeight Canvas height to record (see [toSvg]).
     * @param paths The strokes to encode.
     * @return The metadata payload text (not yet wrapped in `<metadata>`/`CDATA` tags).
     */
    private fun encodeMetadata(canvasWidth: Float, canvasHeight: Float, paths: List<PathData>): String {
        val sb = StringBuilder()
        sb.append("W:${canvasWidth},${canvasHeight}\n")
        for (path in paths) {
            val colorHex = path.color.toArgb().toUInt().toString(16).padStart(8, '0')
            sb.append("S:${path.id}|$colorHex|${path.thickness}\n")
            for (o in path.paths) {
                sb.append("${o.x},${o.y}\n")
            }
        }
        return sb.toString()
    }

    /**
     * Parses the embedded `<metadata>` CDATA block (see [encodeMetadata] for the format)
     * back into a full-fidelity [DrawingData], if present and well-formed. This is the
     * sole source of truth for [fromSvg] — no other part of the SVG is read.
     *
     * @param svg The SVG document string.
     * @return The reconstructed [DrawingData], or `null` if there is no metadata
     *   block, it's empty, or any line fails to parse (malformed/truncated/foreign
     *   data) — signaling the caller to treat the attachment as non-editable.
     */
    private fun parseMetadata(svg: String): DrawingData? {
        val raw = CDATA_REGEX.find(svg)?.groupValues?.get(1) ?: return null
        val lines = raw.split('\n').map { it.trim() }.filter { it.isNotEmpty() }
        if (lines.isEmpty()) return null

        val result = mutableListOf<PathData>()
        var canvasWidth = 0f
        var canvasHeight = 0f
        var currentId = ""
        var currentColor = Color.Black
        var currentThickness = 0f
        var currentPoints = mutableListOf<Offset>()
        var hasOpenStroke = false

        fun flush() {
            if (hasOpenStroke) {
                result.add(
                    PathData(
                        id = currentId,
                        color = currentColor,
                        thickness = currentThickness,
                        paths = currentPoints.toList()
                    )
                )
            }
        }

        try {
            for (line in lines) {
                when {
                    line.startsWith("W:") -> {
                        val parts = line.removePrefix("W:").split(',')
                        canvasWidth = parts[0].toFloat()
                        canvasHeight = parts[1].toFloat()
                    }
                    line.startsWith("S:") -> {
                        flush()
                        currentPoints = mutableListOf()
                        val parts = line.removePrefix("S:").split('|')
                        currentId = parts[0]
                        currentColor = Color((parts[1].toULong(16)).toInt())
                        currentThickness = parts[2].toFloat()
                        hasOpenStroke = true
                    }
                    else -> {
                        val parts = line.split(',')
                        currentPoints.add(Offset(x = parts[0].toFloat(), y = parts[1].toFloat()))
                    }
                }
            }
            flush()

            if (canvasWidth == 0f || canvasHeight == 0f) {
                val (boundW, boundH) = boundingSize(result)
                canvasWidth = boundW
                canvasHeight = boundH
            }
        } catch (e: Exception) {
            // Malformed or foreign metadata — signal "not editable" rather than guessing.
            return null
        }

        return DrawingData(result.toList(), canvasWidth, canvasHeight)
    }

    // -----------------------------------------------------------------
    // Number formatting without java.util.Locale / String.format
    // -----------------------------------------------------------------

    /**
     * Formats a [Float] as a compact decimal string (rounded to 2 decimal places, with
     * trailing `.0` dropped for whole numbers) without relying on `java.util.Locale` or
     * `String.format`, neither of which is safely available across all Kotlin Multiplatform
     * targets.
     *
     * @receiver The value to format.
     * @return The formatted string, e.g. `12.3`, `100`, `-4.05`.
     */
    private fun Float.fmt(): String {
        val rounded = round(this * 100f) / 100f
        return if (rounded == rounded.toLong().toFloat()) {
            rounded.toLong().toString()
        } else {
            rounded.toString()
        }
    }
}