package at.techbee.spectacled.theme.journals

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme

val lightJournalsScheme = lightColorScheme(
    primary = JournalsColors.primaryLight,
    onPrimary = JournalsColors.onPrimaryLight,
    primaryContainer = JournalsColors.primaryContainerLight,
    onPrimaryContainer = JournalsColors.onPrimaryContainerLight,
    secondary = JournalsColors.secondaryLight,
    onSecondary = JournalsColors.onSecondaryLight,
    secondaryContainer = JournalsColors.secondaryContainerLight,
    onSecondaryContainer = JournalsColors.onSecondaryContainerLight,
    tertiary = JournalsColors.tertiaryLight,
    onTertiary = JournalsColors.onTertiaryLight,
    tertiaryContainer = JournalsColors.tertiaryContainerLight,
    onTertiaryContainer = JournalsColors.onTertiaryContainerLight,
    error = JournalsColors.errorLight,
    onError = JournalsColors.onErrorLight,
    errorContainer = JournalsColors.errorContainerLight,
    onErrorContainer = JournalsColors.onErrorContainerLight,
    background = JournalsColors.backgroundLight,
    onBackground = JournalsColors.onBackgroundLight,
    surface = JournalsColors.surfaceLight,
    onSurface = JournalsColors.onSurfaceLight,
    surfaceVariant = JournalsColors.surfaceVariantLight,
    onSurfaceVariant = JournalsColors.onSurfaceVariantLight,
    outline = JournalsColors.outlineLight,
    outlineVariant = JournalsColors.outlineVariantLight,
    scrim = JournalsColors.scrimLight,
    inverseSurface = JournalsColors.inverseSurfaceLight,
    inverseOnSurface = JournalsColors.inverseOnSurfaceLight,
    inversePrimary = JournalsColors.inversePrimaryLight,
    surfaceDim = JournalsColors.surfaceDimLight,
    surfaceBright = JournalsColors.surfaceBrightLight,
    surfaceContainerLowest = JournalsColors.surfaceContainerLowestLight,
    surfaceContainerLow = JournalsColors.surfaceContainerLowLight,
    surfaceContainer = JournalsColors.surfaceContainerLight,
    surfaceContainerHigh = JournalsColors.surfaceContainerHighLight,
    surfaceContainerHighest = JournalsColors.surfaceContainerHighestLight,
)

val darkJournalsScheme = darkColorScheme(
    primary = JournalsColors.primaryDark,
    onPrimary = JournalsColors.onPrimaryDark,
    primaryContainer = JournalsColors.primaryContainerDark,
    onPrimaryContainer = JournalsColors.onPrimaryContainerDark,
    secondary = JournalsColors.secondaryDark,
    onSecondary = JournalsColors.onSecondaryDark,
    secondaryContainer = JournalsColors.secondaryContainerDark,
    onSecondaryContainer = JournalsColors.onSecondaryContainerDark,
    tertiary = JournalsColors.tertiaryDark,
    onTertiary = JournalsColors.onTertiaryDark,
    tertiaryContainer = JournalsColors.tertiaryContainerDark,
    onTertiaryContainer = JournalsColors.onTertiaryContainerDark,
    error = JournalsColors.errorDark,
    onError = JournalsColors.onErrorDark,
    errorContainer = JournalsColors.errorContainerDark,
    onErrorContainer = JournalsColors.onErrorContainerDark,
    background = JournalsColors.backgroundDark,
    onBackground = JournalsColors.onBackgroundDark,
    surface = JournalsColors.surfaceDark,
    onSurface = JournalsColors.onSurfaceDark,
    surfaceVariant = JournalsColors.surfaceVariantDark,
    onSurfaceVariant = JournalsColors.onSurfaceVariantDark,
    outline = JournalsColors.outlineDark,
    outlineVariant = JournalsColors.outlineVariantDark,
    scrim = JournalsColors.scrimDark,
    inverseSurface = JournalsColors.inverseSurfaceDark,
    inverseOnSurface = JournalsColors.inverseOnSurfaceDark,
    inversePrimary = JournalsColors.inversePrimaryDark,
    surfaceDim = JournalsColors.surfaceDimDark,
    surfaceBright = JournalsColors.surfaceBrightDark,
    surfaceContainerLowest = JournalsColors.surfaceContainerLowestDark,
    surfaceContainerLow = JournalsColors.surfaceContainerLowDark,
    surfaceContainer = JournalsColors.surfaceContainerDark,
    surfaceContainerHigh = JournalsColors.surfaceContainerHighDark,
    surfaceContainerHighest = JournalsColors.surfaceContainerHighestDark,
)
