package at.techbee.spectacled.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme

val lightNotesScheme = lightColorScheme(
    primary = NotesColors.primaryLight,
    onPrimary = NotesColors.onPrimaryLight,
    primaryContainer = NotesColors.primaryContainerLight,
    onPrimaryContainer = NotesColors.onPrimaryContainerLight,
    secondary = NotesColors.secondaryLight,
    onSecondary = NotesColors.onSecondaryLight,
    secondaryContainer = NotesColors.secondaryContainerLight,
    onSecondaryContainer = NotesColors.onSecondaryContainerLight,
    tertiary = NotesColors.tertiaryLight,
    onTertiary = NotesColors.onTertiaryLight,
    tertiaryContainer = NotesColors.tertiaryContainerLight,
    onTertiaryContainer = NotesColors.onTertiaryContainerLight,
    error = NotesColors.errorLight,
    onError = NotesColors.onErrorLight,
    errorContainer = NotesColors.errorContainerLight,
    onErrorContainer = NotesColors.onErrorContainerLight,
    background = NotesColors.backgroundLight,
    onBackground = NotesColors.onBackgroundLight,
    surface = NotesColors.surfaceLight,
    onSurface = NotesColors.onSurfaceLight,
    surfaceVariant = NotesColors.surfaceVariantLight,
    onSurfaceVariant = NotesColors.onSurfaceVariantLight,
    outline = NotesColors.outlineLight,
    outlineVariant = NotesColors.outlineVariantLight,
    scrim = NotesColors.scrimLight,
    inverseSurface = NotesColors.inverseSurfaceLight,
    inverseOnSurface = NotesColors.inverseOnSurfaceLight,
    inversePrimary = NotesColors.inversePrimaryLight,
    surfaceDim = NotesColors.surfaceDimLight,
    surfaceBright = NotesColors.surfaceBrightLight,
    surfaceContainerLowest = NotesColors.surfaceContainerLowestLight,
    surfaceContainerLow = NotesColors.surfaceContainerLowLight,
    surfaceContainer = NotesColors.surfaceContainerLight,
    surfaceContainerHigh = NotesColors.surfaceContainerHighLight,
    surfaceContainerHighest = NotesColors.surfaceContainerHighestLight,
)

val darkNotesScheme = darkColorScheme(
    primary = NotesColors.primaryDark,
    onPrimary = NotesColors.onPrimaryDark,
    primaryContainer = NotesColors.primaryContainerDark,
    onPrimaryContainer = NotesColors.onPrimaryContainerDark,
    secondary = NotesColors.secondaryDark,
    onSecondary = NotesColors.onSecondaryDark,
    secondaryContainer = NotesColors.secondaryContainerDark,
    onSecondaryContainer = NotesColors.onSecondaryContainerDark,
    tertiary = NotesColors.tertiaryDark,
    onTertiary = NotesColors.onTertiaryDark,
    tertiaryContainer = NotesColors.tertiaryContainerDark,
    onTertiaryContainer = NotesColors.onTertiaryContainerDark,
    error = NotesColors.errorDark,
    onError = NotesColors.onErrorDark,
    errorContainer = NotesColors.errorContainerDark,
    onErrorContainer = NotesColors.onErrorContainerDark,
    background = NotesColors.backgroundDark,
    onBackground = NotesColors.onBackgroundDark,
    surface = NotesColors.surfaceDark,
    onSurface = NotesColors.onSurfaceDark,
    surfaceVariant = NotesColors.surfaceVariantDark,
    onSurfaceVariant = NotesColors.onSurfaceVariantDark,
    outline = NotesColors.outlineDark,
    outlineVariant = NotesColors.outlineVariantDark,
    scrim = NotesColors.scrimDark,
    inverseSurface = NotesColors.inverseSurfaceDark,
    inverseOnSurface = NotesColors.inverseOnSurfaceDark,
    inversePrimary = NotesColors.inversePrimaryDark,
    surfaceDim = NotesColors.surfaceDimDark,
    surfaceBright = NotesColors.surfaceBrightDark,
    surfaceContainerLowest = NotesColors.surfaceContainerLowestDark,
    surfaceContainerLow = NotesColors.surfaceContainerLowDark,
    surfaceContainer = NotesColors.surfaceContainerDark,
    surfaceContainerHigh = NotesColors.surfaceContainerHighDark,
    surfaceContainerHighest = NotesColors.surfaceContainerHighestDark,
)
