name: Create and upload app bundles to Google Play
on:
  push:
    tags:
      - 'v*'           # alpha, beta and final releases all upload to Google Play
  workflow_dispatch:
jobs:
  build:
    name: Upload app bundles to Google Play
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
      - uses: gradle/actions/setup-gradle@v6.2.0

      - name: Prepare keystore
        run: echo "${{ secrets.android_keystore_base64 }}" | base64 -d > "$GITHUB_WORKSPACE/keystore.jks"

      - name: Verify keystore
        run: |
          ls -lh "$GITHUB_WORKSPACE/keystore.jks"
          keytool -list \
            -keystore "$GITHUB_WORKSPACE/keystore.jks" \
            -storepass "${{ secrets.android_keystore_password }}"

      - name: Build spectacled release app bundles (AAB) for Gplay
        run: ./gradlew androidJournalsApp:bundleRelease androidNotesApp:bundleRelease androidTasksApp:bundleRelease
        env:
          ANDROID_KEYSTORE: ${{ github.workspace }}/keystore.jks
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.android_keystore_password }}
          ANDROID_KEY_ALIAS_JOURNALS: ${{ secrets.android_key_alias_journals }}
          ANDROID_KEY_PASSWORD_JOURNALS: ${{ secrets.android_key_password_journals }}
          ANDROID_KEY_ALIAS_NOTES: ${{ secrets.android_key_alias_notes }}
          ANDROID_KEY_PASSWORD_NOTES: ${{ secrets.android_key_password_notes }}
          ANDROID_KEY_ALIAS_TASKS: ${{ secrets.android_key_alias_tasks }}
          ANDROID_KEY_PASSWORD_TASKS: ${{ secrets.android_key_password_tasks }}

      - name: Upload spectacled Journals to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.google_play_service_account_json }}
          packageName: at.techbee.spectacled.journals
          releaseFiles: ./androidJournalsApp/build/outputs/bundle/release/*.aab
          tracks: internal
          status: completed

      - name: Upload spectacled Notes to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.google_play_service_account_json }}
          packageName: at.techbee.spectacled.notes
          releaseFiles: ./androidNotesApp/build/outputs/bundle/release/*.aab
          tracks: internal
          status: completed

      - name: Upload spectacled Tasks to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.google_play_service_account_json }}
          packageName: at.techbee.spectacled.tasks
          releaseFiles: ./androidTasksApp/build/outputs/bundle/release/*.aab
          tracks: internal
          status: completed
